[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activityCompose = "1.11.0"
androidx-core-uri = "1.1.0-alpha03"
androidx-lifecycle = "2.9.5"
androidx-navigation-compose = "2.9.1"
compose-plugin = "1.9.1"
htmlconverter = "1.1.0"
image-picker-kmp = "1.0.27"
kamel = "1.0.8"
kotlin = "2.2.21"
kotlinx-datetime = "0.7.1"
kotlinx-serialization-json = "1.9.0"
koin = "4.1.1"
material-icons = "1.7.3"
zoomable = "2.8.2"
#Gradle
gradlePlugins-crashlytics = "3.0.6"
gradlePlugins-google-services = "4.4.4"
#Gitlive
firebase-gitlive-sdk = "2.3.0"

[libraries]
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-uri = { group = "org.jetbrains.androidx.core", name = "core-uri", version.ref = "androidx-core-uri" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
digitalia-htmlconverter = { group = "be.digitalia.compose.htmlconverter", name = "htmlconverter", version.ref = "htmlconverter" }
kamel-image = { group = "media.kamel", name = "kamel-image-default", version.ref = "kamel" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
image-picker-kmp = { group = "io.github.ismoy", name = "imagepickerkmp", version.ref = "image-picker-kmp" }
material-icons-extended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "material-icons" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }

#Gitlive
gitlive-firebase-kotlin-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "firebase-gitlive-sdk" }
gitlive-firebase-kotlin-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase-gitlive-sdk" }
gitlive-firebase-kotlin-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase-gitlive-sdk" }
gitlive-firebase-kotlin-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase-gitlive-sdk" }
gitlive-firebase-kotlin-storage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase-gitlive-sdk" }
gitlive-firebase-kotlin-functions = { module = "dev.gitlive:firebase-functions", version.ref = "firebase-gitlive-sdk" }

# Koin dependencies
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-composeVM = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradlePlugins-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "gradlePlugins-google-services" }
